### ISSUE TITLE
Batoto "found 0 items"

### ISSUE THREAD

**Issue by samishii23** [fake-name/MangaCMS#22]
I know Batoto is dead... But I was hoping to be able to scrape some series from there before it shuts down. Is there anyway I could figure this 'bug' out? It just sounds like another layer of security that the owner applied at some point to stop scraping... Giving all the dependencies you have, I wouldn't be able to trace this down myself in 4 days... lol. So just wondering...
( now that its shutting down, it seems like a waste to not want to share it all... frustrated by the owner's decision on that matter )

`Main.Bts.Se - INFO - Found 0 items for %series_name%, 0 were new.`

**Comment by fake-name** [comment]
How did you get that output?

The Batoto `SeriesEnqueuer` class operates on the results the Batoto SeriesLoader adds to the database, so if that hasn't run, it won't have anything to do.

**Comment by samishii23** [comment]
Sorry, that was me be a bit generic in the description. 

This is the output that is happening right now.

`Main.BtS.Se.Web - INFO - Request for URL: http://bato.to/comic/_/comics/hokenshitsu-no-kageyama-kun-r20717 succeeded at Mon Jan 15 00:33:40 2018 On Attempt 2. Recieving...`
`Main.BtS.Se.Web - INFO - URL fully retrieved.`
`Main.BtS.Se.Web - INFO - Compression type = gzip. Content Size compressed = 20.378K.`
`Decompressed = 103.659K. File type: text/html;charset=UTF-8.`
`Main.BtS.Se - INFO - Found 0 items for Hokenshitsu no Kageyama-kun, 0 were new.`
`Main.BtS.Se - INFO - Loading items for series 'Houkage no Ikemengohan'`
`Main.BtS.Se.Web - INFO - Fetching content at URL: http://bato.to/comic/_/comics/houkage-no-ikemengohan-r23039`

These are the only plug-ins i have enabled at the moment, wanted to focus on Batoto.

0   : (MangaCMS.ScrapePlugins.M.BtBaseManager.Run,           hours( 1)),
1   : (MangaCMS.ScrapePlugins.M.MangaStreamLoader.Run,   hours( 1)),
2   : (MangaCMS.ScrapePlugins.M.BuMonitor.Run,                     hours( 1)),
11  : (MangaCMS.ScrapePlugins.M.McLoader.Run,                    hours(12)), 
12  : (MangaCMS.ScrapePlugins.M.IrcGrabber.IrcEnqueueRun,            hours(12)),  
15  : (MangaCMS.ScrapePlugins.M.IrcGrabber.BotRunner,

**Comment by fake-name** [comment]
Have you gone to `http://bato.to/comic/_/comics/houkage-no-ikemengohan-r23039`? Because that series has no releases.

**Comment by samishii23** [comment]
It has 1 release. Which is also a public release. 
But, I watched it do a couple of series I have have involvement in, and know they are on Batoto. Same thing. Found 0 items. Looking at the database too, I have 86 line items in the **public.batotoseries** table.

**Comment by fake-name** [comment]
Yeah, the series tracker had a dumb bug where it was looking for `http://` specific addresses. The normal release monitor thing would then catch almost everything anyways, but it was dumb.

**Comment by samishii23** [comment]
Thanks again! Appreciate you taking the time to help a random person!

**Comment by fake-name** [comment]
I don't mind, it was a legit issue that I had missed.

**Comment by fake-name** [comment]
Also wow, yeah, apparently shit was broke. Apparently bs4 + regexes = fail. Huh.

**Comment by samishii23** [comment]
Well, glad to hear that more stuff is being fixed. :)

**Comment by samishii23** [comment]
On the topic of Batoto. Just wondering for a more grace full error message on batoto. usually a couple screens worth of error when Batoto kicks the bot login session out. Maybe too that can be refreshed now that I think about it. Cause it does stop the scanning and collecting threads.


Main.Manga.Bt.Run - CRITICAL - Uncaught major exception in plugin!
Main.Manga.Bt.Run - CRITICAL - Traceback:
Main.Manga.Bt.Run - CRITICAL - Traceback (most recent call last):
Main.Manga.Bt.Run - CRITICAL -   File "/home/samishii/Downloads/MangaCMS/MangaCMS/ScrapePlugins/RunBase.py", line 98, in go
Main.Manga.Bt.Run - CRITICAL -     self._go()
Main.Manga.Bt.Run - CRITICAL -   File "/home/samishii/Downloads/MangaCMS/MangaCMS/ScrapePlugins/RunBase.py", line 121, in _go
Main.Manga.Bt.Run - CRITICAL -     fl.do_fetch_feeds()
Main.Manga.Bt.Run - CRITICAL -   File "/home/samishii/Downloads/MangaCMS/MangaCMS/ScrapePlugins/LoaderBase.py", line 85, in do_fetch_feeds
Main.Manga.Bt.Run - CRITICAL -     self.setup()
Main.Manga.Bt.Run - CRITICAL -   File "/home/samishii/Downloads/MangaCMS/MangaCMS/ScrapePlugins/M/BtLoader/DbLoader.py", line 258, in setup
Main.Manga.Bt.Run - CRITICAL -     checkLogin(self.wg)
Main.Manga.Bt.Run - CRITICAL -   File "/home/samishii/Downloads/MangaCMS/MangaCMS/ScrapePlugins/M/BtLoader/common.py", line 45, in checkLogin
Main.Manga.Bt.Run - CRITICAL -     raise ValueError("Failed to log in!")
Main.Manga.Bt.Run - CRITICAL - ValueError: Failed to log in!
Main.Manga.Bt.Run - CRITICAL - 
Main.Manga.Bt.Run - INFO - BtLoader finished.
Main.Manga.Bt.Base - CRITICAL - Uncaught major exception in plugin!
Main.Manga.Bt.Base - CRITICAL - Traceback:
Main.Manga.Bt.Base - CRITICAL - Traceback (most recent call last):
Main.Manga.Bt.Base - CRITICAL -   File "/home/samishii/Downloads/MangaCMS/MangaCMS/ScrapePlugins/RunBase.py", line 98, in go
Main.Manga.Bt.Base - CRITICAL -     self._go()
Main.Manga.Bt.Base - CRITICAL -   File "/home/samishii/Downloads/MangaCMS/MangaCMS/ScrapePlugins/M/BtBaseManager/Run.py", line 31, in _go
Main.Manga.Bt.Base - CRITICAL -     loader.go()
Main.Manga.Bt.Base - CRITICAL -   File "/home/samishii/Downloads/MangaCMS/MangaCMS/ScrapePlugins/RunBase.py", line 98, in go
Main.Manga.Bt.Base - CRITICAL -     self._go()
Main.Manga.Bt.Base - CRITICAL -   File "/home/samishii/Downloads/MangaCMS/MangaCMS/ScrapePlugins/RunBase.py", line 121, in _go
Main.Manga.Bt.Base - CRITICAL -     fl.do_fetch_feeds()
Main.Manga.Bt.Base - CRITICAL -   File "/home/samishii/Downloads/MangaCMS/MangaCMS/ScrapePlugins/LoaderBase.py", line 85, in do_fetch_feeds
Main.Manga.Bt.Base - CRITICAL -     self.setup()
Main.Manga.Bt.Base - CRITICAL -   File "/home/samishii/Downloads/MangaCMS/MangaCMS/ScrapePlugins/M/BtLoader/DbLoader.py", line 258, in setup
Main.Manga.Bt.Base - CRITICAL -     checkLogin(self.wg)
Main.Manga.Bt.Base - CRITICAL -   File "/home/samishii/Downloads/MangaCMS/MangaCMS/ScrapePlugins/M/BtLoader/common.py", line 45, in checkLogin
Main.Manga.Bt.Base - CRITICAL -     raise ValueError("Failed to log in!")
Main.Manga.Bt.Base - CRITICAL - ValueError: Failed to log in!
Main.Manga.Bt.Base - CRITICAL - 
Main.Manga.Bt.Base - INFO - BtBase finished.
Job "callMod (trigger: interval[0:09:00], next run at: 2018-01-15 09:15:22 EST)" raised an exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "mainScrape.py", line 66, in callMod
    instance.go()
  File "/home/samishii/Downloads/MangaCMS/MangaCMS/ScrapePlugins/RunBase.py", line 98, in go
    self._go()
  File "/home/samishii/Downloads/MangaCMS/MangaCMS/ScrapePlugins/M/BtBaseManager/Run.py", line 31, in _go
    loader.go()
  File "/home/samishii/Downloads/MangaCMS/MangaCMS/ScrapePlugins/RunBase.py", line 98, in go
    self._go()
  File "/home/samishii/Downloads/MangaCMS/MangaCMS/ScrapePlugins/RunBase.py", line 121, in _go
    fl.do_fetch_feeds()
  File "/home/samishii/Downloads/MangaCMS/MangaCMS/ScrapePlugins/LoaderBase.py", line 85, in do_fetch_feeds
    self.setup()
  File "/home/samishii/Downloads/MangaCMS/MangaCMS/ScrapePlugins/M/BtLoader/DbLoader.py", line 258, in setup
    checkLogin(self.wg)
  File "/home/samishii/Downloads/MangaCMS/MangaCMS/ScrapePlugins/M/BtLoader/common.py", line 45, in checkLogin
    raise ValueError("Failed to log in!")
ValueError: Failed to log in!

**Comment by fake-name** [comment]
Yeah, the barf on plugin login failure is kind of ugly.

Ideally, I should have a special exception for login failure that is caught and propagated somewhat more cleanly, but I have't been bothered by it enough. After all, if your login is wrong, you **really** want to know about it.

**Comment by samishii23** [comment]
In my case the scraper processes about 10-15 urls and links before the login gets rejected. Was just thinking to myself about making the error 1 or 2 red lines. Maybe have a couple more login attempts to continue, if not fail to the default interval refresh rate... just my 2 cents...

**Comment by fake-name** [comment]
That's..... very strange. I get no bounces after successful login at all. I've had the scraper running for multiple days now continuously without issue.

**Comment by samishii23** [comment]
Its done this since I started running the script on saturday... I have a valid batoto account, and even logged in multiple times on various browsers on a couple different boxes to check and make sure I haven't been banned... not sure... not that i would expect this, but i'd offer you to see it yourself if it was possible. since i setup this box just for the scraping.

But hmm. Looking at the web interface... Theres no series in the batoto category. So I guess its not downloading then... well darn

**Comment by fake-name** [comment]
It won't actually do any downloading until the series scanner has walked every series it found, which will take a *while* (there's ~9.7K series on batoto).

The design behind the scraper was to track series to minimize the rewalking of series pages (and it did do that fine), but the no-data startup will take quite a fair bit of time.

**Comment by samishii23** [comment]
Well, guess thats out of the picture then. 126 entries since saturday.

**Comment by samishii23** [comment]
Answer to your first db query: 3966, the 2nd: 0.
PhantomJS is installed and up to date.

Here is the latest before the error struck. Don't know if it helps.

Main.BtS.Se - INFO - Loading items for series 'Yaonie jiaozhu kuai tang xia'
Main.BtS.Se.Web - INFO - Fetching content at URL: http://bato.to/comic/_/comics/yaonie-jiaozhu-kuai-tang-xia-r22276
Main.NSLookup - INFO - Refresh call! for fsName->buId mapping cache.
Main.NSLookup - INFO - Refresh call complete. Have 0 keys
Main.NSLookup - INFO - Refresh call! for buId->name mapping cache.
Main.NSLookup - INFO - Refresh call! for buId->buName mapping cache.
Main.NSLookup - INFO - Refresh call! for buName->buId mapping cache.
Main.DirLookup - INFO - Refresh call! for dirMonitor system.
DirDicts not stale!
Main.DirLookup - INFO - DirMonitor system refreshed.
Main.NSLookup - INFO - Refresh call complete. Have 290 keys
Main.NSLookup - INFO - Refresh call complete. Have 290 keys
Main.NSLookup - INFO - Refresh call complete. Have 0 keys
Main.BtS.Se.Web - INFO - Request for URL: http://bato.to/comic/_/comics/yaonie-jiaozhu-kuai-tang-xia-r22276 succeeded at Mon Jan 15 22:46:42 2018 On Attempt 1. Recieving...
Main.BtS.Se.Web - INFO - URL fully retrieved.
Main.BtS.Se.Web - INFO - Compression type = gzip. Content Size compressed = 20.764K. Decompressed = 107.543K. File type: text/html;charset=UTF-8.
Main.BtS.Se - INFO - Found 4 table rows
Main.BtS.Se - INFO - Found 4 items for Yaonie jiaozhu kuai tang xia, 0 were new.
Main.BtS.Se - INFO - Complete
Main.Manga.BtS.Run - INFO - BtEnqueue finished.
Main.Manga.Bt.Base - INFO - BtBase calling Downloader.
Main.Manga.Bt.Run - INFO - Loading BtLoader Runner
BtLoader
Main.Manga.Bt.Run - INFO - BtLoader is running = 'False', as bool = 'False'
Main.Manga.Bt.Run - INFO - BtLoader Started.
Main.Manga.Bt.Run - INFO - Checking Batoto feeds for updates
Main.Manga.Bt.Fl - INFO - Using graphite prefix str: 'MangaCMS.Scrapers.MangaItems.Main.Manga.Bt.Fl'
Main.Manga.Bt.Fl - INFO - Loading Batoto Link Retreiver Runner BaseClass
Main.Manga.Bt.Fl - INFO - Retreived page database created
Main.Manga.Bt.Fl - INFO - Resetting stuck downloads in DB
Main.Manga.Bt.Fl - INFO - Download reset complete
Main.Manga.Bt.Fl.Web - INFO - Fetching content at URL: https://bato.to/forums/index.php?app=core&module=global&section=login
Main.Manga.Bt.Fl.Web - WARNING - Error opening page: https://bato.to/forums/index.php?app=core&module=global&section=login at Mon Jan 15 22:46:42 2018 On Attempt 1.
Main.Manga.Bt.Fl.Web - WARNING - Error Code: HTTP Error 503: Service Temporarily Unavailable
Main.Manga.Bt.Fl.Web - WARNING - Original URL: https://bato.to/forums/index.php?app=core&module=global&section=login
Main.Manga.Bt.Fl.Web - WARNING - Cloudflare failure! Doing automatic step-through.
Main.Manga.Bt.Fl.Web - INFO - Attempting to access page through cloudflare browser verification.
/usr/local/lib/python3.6/dist-packages/selenium/webdriver/phantomjs/webdriver.py:49: UserWarning: Selenium support for PhantomJS has been deprecated, please use headless versions of Chrome or Firefox instead
  warnings.warn('Selenium support for PhantomJS has been deprecated, please use headless '
Main.Manga.Bt.Fl.Web - INFO - Successfully accessed main page!
Main.Manga.Bt.Fl.Web - INFO - Updating cookie!
Main.Manga.Bt.Fl.Web - INFO - Updating cookie!
Main.Manga.Bt.Fl.Web - INFO - Updating cookie!
Main.Manga.Bt.Fl.Web - INFO - Cloudflare access return: True
Main.Manga.Bt.Fl.Web - INFO - Request for URL: https://bato.to/forums/index.php?app=core&module=global&section=login succeeded at Mon Jan 15 22:46:49 2018 On Attempt 2. Recieving...
Main.Manga.Bt.Fl.Web - INFO - URL fully retrieved.
Main.Manga.Bt.Fl.Web - INFO - Compression type = gzip. Content Size compressed = 30.376K. Decompressed = 145.217K. File type: text/html;charset=UTF-8.
Main.Manga.Bt.Fl.Web - INFO - Fetching content at URL: https://bato.to/forums/index.php?app=core&module=global&section=login&do=process
Main.Manga.Bt.Fl.Web - INFO - Making a post-request! Params: '{'auth_key': '880ea6a14ea49e853634fbdc5015a024', 'ips_username': 'samishii23', 'ips_password': 'f4a63f73aa685f2', 'rememberMe': '1'}'
Main.Manga.Bt.Fl.Web - INFO - Request for URL: https://bato.to/forums/index.php?app=core&module=global&section=login&do=process succeeded at Mon Jan 15 22:46:51 2018 On Attempt 1. Recieving...
Main.Manga.Bt.Fl.Web - INFO - URL fully retrieved.
Main.Manga.Bt.Fl.Web - INFO - Compression type = gzip. Content Size compressed = 38.685K. Decompressed = 238.295K. File type: text/html;charset=UTF-8.
Main.Manga.Bt.Run - CRITICAL - Uncaught major exception in plugin!

**Comment by fake-name** [comment]
Uh, maybe edit your password in that.

**Comment by fake-name** [comment]
Is there any chance your username on batoto is of a different case?

**Comment by fake-name** [comment]
Maybe change that password if you use it elsewhere. 

I added some case-fiddling to see if the problem is the login-checker looking for the wrong login casing.

**Comment by samishii23** [comment]
I don't. I pull passwords from a 512 bit string when i need new passwords. Not likely its used else where.

**Comment by samishii23** [comment]
No change in the failed login.
Also it never hits the new log catch message on line 29 of common.py

**Comment by fake-name** [comment]
Yeah, I have no idea what's going on, then. 

I'd nuke my cookies and try re-authing, but it's currently running and I don't want to break anything. Sorry!

**Comment by fake-name** [comment]
Ok, so at some point someone added another field to the login. Lets see if this helps.

**Comment by samishii23** [comment]
Well, Im narrowing the issue down to the **BuMonitor.common.checkLogin()** ... the soup.find() are returning a "None" value. Im in the BS4 docs and trying a few things...

**Comment by fake-name** [comment]
`soup.find("a", id='user_link')` is searching for a `<a>` tag with a `id` attribute of `user_link`.

In my case, it finds a tag: `<a id="user_link" href="https://bato.to/forums/user/<snip-userid>/" title="Your Profile" data-vivaldi-spatnav-clickable="1">Welcome, <snip-username> &nbsp;<span id="user_link_dd"></span></a>`

Do you have batoto set to english? I'm not sure if that would change for other languages (can you even change the language?).

**Comment by samishii23** [comment]
the `login = wg.getSoup(...)` was returning None for the user_link search.
I did a `login.html` dump to the terminal, and seen it was a redirection page that was being displayed rather than the forum home page... running a direct hack to the forum board instead to see if that works...

**Comment by fake-name** [comment]
I dropped all my local cookies and it still resolves properly:

```
Main.Manga.Bt.Fl - INFO - Using graphite prefix str: 'MangaCMS.Scrapers.MangaItems.Main.Manga.Bt.Fl'
Main.Manga.Bt.Fl - INFO - Loading Batoto Link Retreiver Runner BaseClass
Main.Manga.Bt.Fl - INFO - Retreived page database created
Main.Manga.Bt.Fl - INFO - Resetting stuck downloads in DB
Main.Manga.Bt.Fl - INFO - Download reset complete
Main.Manga.Bt.Fl.Web - INFO - Fetching content at URL: https://bato.to/forums/index.php?app=core&module=global&section=login
Main.Manga.Bt.Fl.Web - WARNING - Error opening page: https://bato.to/forums/index.php?app=core&module=global&section=login at Tue Jan 16 06:53:35 2018 On Attempt 1.
Main.Manga.Bt.Fl.Web - WARNING - Error Code: HTTP Error 503: Service Temporarily Unavailable
Main.Manga.Bt.Fl.Web - WARNING - Original URL: https://bato.to/forums/index.php?app=core&module=global&section=login
Main.Manga.Bt.Fl.Web - WARNING - Cloudflare failure! Doing automatic step-through.
Main.Manga.Bt.Fl.Web - INFO - Attempting to access page through cloudflare browser verification.
Main.Manga.Bt.Fl.Web - INFO - Successfully accessed main page!
Main.Manga.Bt.Fl.Web - INFO - Updating cookie!
Main.Manga.Bt.Fl.Web - INFO - Updating cookie!
Main.Manga.Bt.Fl.Web - INFO - Updating cookie!
Main.Manga.Bt.Fl.Web - INFO - Cloudflare access return: True
Main.Manga.Bt.Fl.Web - INFO - Request for URL: https://bato.to/forums/index.php?app=core&module=global&section=login succeeded at Tue Jan 16 06:53:43 2018 On Attempt 2. Recieving...
Main.Manga.Bt.Fl.Web - INFO - URL fully retrieved.
Main.Manga.Bt.Fl.Web - INFO - Compression type = gzip. Content Size compressed = 30.332K. Decompressed = 145.217K. File type: text/html;charset=UTF-8.
Main.Manga.Bt.Fl.Web - INFO - Fetching content at URL: https://bato.to/forums/index.php?app=core&module=global&section=login&do=process
Main.Manga.Bt.Fl.Web - INFO - Making a post-request! Params: '{'rememberMe': '1', 'ips_username': '<snip>', 'auth_key': '880ea6a14ea49e853634fbdc5015a024', 'referer': 'https://bato.to/forums/index.php?app=core&amp;module=global&amp;section=login', 'ips_password': '<snip>'}'
Main.Manga.Bt.Fl.Web - INFO - Request for URL: https://bato.to/forums/index.php?app=core&module=global&section=login&do=process succeeded at Tue Jan 16 06:53:44 2018 On Attempt 1. Recieving...
Main.Manga.Bt.Fl.Web - INFO - URL fully retrieved.
Main.Manga.Bt.Fl.Web - INFO - Compression type = gzip. Content Size compressed = 39.256K. Decompressed = 240.212K. File type: text/html;charset=UTF-8.
Logged in successfully

```

I wonder if they've got extra cloudflare shit on your connection or something.

**Comment by fake-name** [comment]
Interesting. If you are already authenticated, it'll throw a 403 error on the login pate. Huh.

**Comment by fake-name** [comment]
Ok, there was an odd case where if you /had/ a login cookie, the login check would barf (because the login page apparently raises a 403 if you are already authenticated),

I *think* this is fixed in https://github.com/fake-name/MangaCMS/commit/31f2dad2ab25d660afd68c7c75b03d25ea0cf89a

**Comment by samishii23** [comment]
Not sure what triggers the 403 header. but if you browse to bato.to, login, hit the back button and click login again. It does throw an error... So logging in after logging in is an error. 

i ran out of ideas to test for. will patch your changes in and see what happens over night. Thanks for you time today!

**Comment by fake-name** [comment]
FWIW, Madokami has a more or less full rip of batoto, and it's *not* planning on dying anytime soon.

**Comment by samishii23** [comment]
Also, still failed on my end. Just happened at the start of the whole process rather than collecting some links first.

**Comment by fake-name** [comment]
Yeah, that could be worth trying.

My concern was there being a "Your login <nnnn> is not correct" message that trips the checking up.

**Comment by samishii23** [comment]
Thats reasonable. I would just check specifically for the bad info page 1st, then look for the above.

> FWIW, Madokami has a more or less full rip of batoto, and it's not planning on dying anytime soon.

If there wasn't 401's everywhere! lol

Side Note: Looks like Bato.to died today. RIP

**Comment by fake-name** [comment]
> If there wasn't 401's everywhere! lol

Bitch in IRC, it'll get fixt.

The server recently asploded, so a lot of junk was broken while it was restored.

**Comment by samishii23** [comment]
plz no ban. lol

**Comment by fake-name** [comment]
Are you sure batoto is down? 

I still seem to be fetching things.

![image](https://user-images.githubusercontent.com/1401239/35023432-7d35457a-faef-11e7-83b1-8d35653685a2.png)

**Comment by samishii23** [comment]
mmm, well when I posted that earlier, I got the Cloudflare offline page... dun know. 
after your change I don't scrape anything anymore since it seems the login is at the start of execution. lol
all good though, after last night I gave up on my plans for batoto... qq

**Comment by fake-name** [comment]
Yeah, sorry I'm not more help. I legit have no idea why it's failing, since it works where I am.

**Comment by samishii23** [comment]
Welp, we'll never know. Oh wells... I appreciate you trying to help though. A last minute valiant effort!
When Im not dead tired from work, i'll chat on irc about all those 401s...

**Comment by fake-name** [comment]
Everyone on IRC is kind of excessively snarky, but I don't think anyone would be bothered by being informed of actual legit site issues.

**Comment by samishii23** [comment]
Well. I haven't even seen the website since a long while ago, last I seen was someone complaining about the the time and money investing in something and he couldn't do it anymore ( sounds familiar, eh? )... and the sticky in the irc channel didn't clarify anything either.

**Comment by fake-name** [comment]
It's kind of opaque intentionally.

Also, registration is currently completely broken by the server move, so... ¯\_(ツ)_/¯

**Comment by samishii23** [comment]
Whats the server backend written in?

**Comment by fake-name** [comment]
Sadness. Sadness and [php](https://github.com/qqueue/MangaIndex).

We're actually looking for contributors, since everyone either doesn't code, or refuses to touch PHP (Heyo!).

**Comment by samishii23** [comment]
Is that the repo for the madokami site? PHP is about the only thing i've actively touched in various projects. So I could probably try and help out.

**Comment by fake-name** [comment]
> Is that the repo for the madokami site?

As far as I know, yes. I'm not involved in actually running the site, so I don't know first-hand.
